### ISSUE TITLE
Unable to update to 1.0.5

### ISSUE THREAD

**Issue by pauloelias** [elivz/VzUrl-Craft#12]
I have not been able to update to 1.0.4 or 1.0.5 from 1.0.3. When I try to run the update the the database migration fails and rolls back to the old DB (see attached screenshot)

![screenshot 2017-02-16 10 32 15](https://cloud.githubusercontent.com/assets/978535/23042666/511909fc-f44e-11e6-974a-e0b4bf478d5f.png)

It looks like this is our problem:

```
failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_videoUrl' in 'craft_content'. The SQL statement executed was: ALTER TABLE `craft_content` CHANGE `field_videoUrl` `field_videoUrl` text NULL.
```

We don't have a `videoUrl` field but we do do have `videoUrl` fields inside Matrix and SuperTable blocks so I am not sure where this is error coming from:

![screenshot 2017-02-16 13 47 45](https://cloud.githubusercontent.com/assets/978535/23042715/8a217b08-f44e-11e6-9227-1fa9472ad240.png)

This is what I can gather from my local logs:

```
2017/02/16 21:28:28 [info] [application] [Forced] The plugin "VZ URL" wants to update the database.
in /home/vagrant/churchill/craft/app/services/UpdatesService.php (745)
in /home/vagrant/churchill/craft/app/controllers/UpdateController.php (405)
in /home/vagrant/churchill/craft/app/etc/web/WebApp.php (931)
2017/02/16 21:28:28 [info] [application] [Forced] Running migrations...
in /home/vagrant/churchill/craft/app/etc/updates/Updater.php (179)
in /home/vagrant/churchill/craft/app/services/UpdatesService.php (746)
in /home/vagrant/churchill/craft/app/controllers/UpdateController.php (405)
2017/02/16 21:28:28 [trace] [system.CModule] Loading "migrations" application component
in /home/vagrant/churchill/craft/app/etc/web/WebApp.php (595)
in /home/vagrant/churchill/craft/app/etc/updates/Updater.php (180)
in /home/vagrant/churchill/craft/app/services/UpdatesService.php (746)
2017/02/16 21:28:28 [trace] [system.db.CDbCommand] Querying SQL: SELECT `version`, `applyTime`
FROM `craft_migrations`
WHERE pluginId = :pluginId
ORDER BY `version` DESC. Bound with :pluginId='102'
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (222)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (265)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (56)
2017/02/16 21:28:28 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SELECT `version`, `applyTime`
FROM `craft_migrations`
WHERE pluginId = :pluginId
ORDER BY `version` DESC. Bound with :pluginId='102')
2017/02/16 21:28:28 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SELECT `version`, `applyTime`
FROM `craft_migrations`
WHERE pluginId = :pluginId
ORDER BY `version` DESC. Bound with :pluginId='102')
2017/02/16 21:28:28 [info] [application] [Forced] Total 1 new migration to be applied for plugin VzUrl:
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (74)
in /home/vagrant/churchill/craft/app/etc/updates/Updater.php (180)
in /home/vagrant/churchill/craft/app/services/UpdatesService.php (746)
2017/02/16 21:28:28 [info] [application] [Forced] m170216_100000_vzurl_to_text_column
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (83)
in /home/vagrant/churchill/craft/app/etc/updates/Updater.php (180)
in /home/vagrant/churchill/craft/app/services/UpdatesService.php (746)
2017/02/16 21:28:28 [info] [application] [Forced] Applying migration: m170216_100000_vzurl_to_text_column for plugin: VzUrl
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (139)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (91)
in /home/vagrant/churchill/craft/app/etc/updates/Updater.php (180)
2017/02/16 21:28:28 [trace] [system.db.CDbConnection] Starting transaction
in /home/vagrant/churchill/craft/app/etc/db/BaseMigration.php (29)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (149)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (91)
2017/02/16 21:28:28 [info] [application] [Forced] Increasing character limit for VZ URL fields.
in /home/vagrant/churchill/craft/plugins/vzurl/migrations/m170216_100000_vzurl_to_text_column.php (17)
in /home/vagrant/churchill/craft/app/etc/db/BaseMigration.php (33)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (149)
2017/02/16 21:28:28 [trace] [system.db.CDbCommand] Querying SQL: SELECT `handle`
FROM `craft_fields`
WHERE `type`=:poqhcj3Bun. Bound with :poqhcj3Bun='VzUrl'
in /home/vagrant/churchill/craft/plugins/vzurl/migrations/m170216_100000_vzurl_to_text_column.php (24)
in /home/vagrant/churchill/craft/app/etc/db/BaseMigration.php (33)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (149)
2017/02/16 21:28:28 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SELECT `handle`
FROM `craft_fields`
WHERE `type`=:poqhcj3Bun. Bound with :poqhcj3Bun='VzUrl')
2017/02/16 21:28:28 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SELECT `handle`
FROM `craft_fields`
WHERE `type`=:poqhcj3Bun. Bound with :poqhcj3Bun='VzUrl')
2017/02/16 21:28:28 [info] [application] Altering column field_videoUrl in table content...
in /home/vagrant/churchill/craft/app/etc/db/BaseMigration.php (215)
in /home/vagrant/churchill/craft/plugins/vzurl/migrations/m170216_100000_vzurl_to_text_column.php (30)
in /home/vagrant/churchill/craft/app/etc/db/BaseMigration.php (33)
2017/02/16 21:28:28 [trace] [system.db.CDbCommand] Executing SQL: ALTER TABLE `craft_content` CHANGE `field_videoUrl` `field_videoUrl` text NULL
in /home/vagrant/churchill/craft/app/etc/db/DbCommand.php (662)
in /home/vagrant/churchill/craft/app/etc/db/BaseMigration.php (217)
in /home/vagrant/churchill/craft/plugins/vzurl/migrations/m170216_100000_vzurl_to_text_column.php (30)
2017/02/16 21:28:28 [profile] [system.db.CDbCommand.execute] begin:system.db.CDbCommand.execute(ALTER TABLE `craft_content` CHANGE `field_videoUrl` `field_videoUrl` text NULL)
2017/02/16 21:28:28 [profile] [system.db.CDbCommand.execute] end:system.db.CDbCommand.execute(ALTER TABLE `craft_content` CHANGE `field_videoUrl` `field_videoUrl` text NULL)
2017/02/16 21:28:28 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_videoUrl' in 'craft_content'. The SQL statement executed was: ALTER TABLE `craft_content` CHANGE `field_videoUrl` `field_videoUrl` text NULL.
in /home/vagrant/churchill/craft/app/etc/db/DbCommand.php (662)
in /home/vagrant/churchill/craft/app/etc/db/BaseMigration.php (217)
in /home/vagrant/churchill/craft/plugins/vzurl/migrations/m170216_100000_vzurl_to_text_column.php (30)
2017/02/16 21:28:28 [error] [application] CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_videoUrl' in 'craft_content'. The SQL statement executed was: ALTER TABLE `craft_content` CHANGE `field_videoUrl` `field_videoUrl` text NULL (/home/vagrant/churchill/craft/app/framework/db/CDbCommand.php:358)
in /home/vagrant/churchill/craft/app/etc/db/BaseMigration.php (54)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (149)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (91)
2017/02/16 21:28:28 [error] [application] #0 /home/vagrant/churchill/craft/app/etc/db/DbCommand.php(662): CDbCommand->execute()
#1 /home/vagrant/churchill/craft/app/etc/db/BaseMigration.php(217): Craft\DbCommand->alterColumn('craft_content', 'field_videoUrl', 'text NULL', NULL, NULL)
#2 /home/vagrant/churchill/craft/plugins/vzurl/migrations/m170216_100000_vzurl_to_text_column.php(30): Craft\BaseMigration->alterColumn('content', 'field_videoUrl', Array)
#3 /home/vagrant/churchill/craft/app/etc/db/BaseMigration.php(33): Craft\m170216_100000_vzurl_to_text_column->safeUp()
#4 /home/vagrant/churchill/craft/app/services/MigrationsService.php(149): Craft\BaseMigration->up()
#5 /home/vagrant/churchill/craft/app/services/MigrationsService.php(91): Craft\MigrationsService->migrateUp('m170216_100000_...', Object(Craft\VzUrlPlugin))
#6 /home/vagrant/churchill/craft/app/etc/updates/Updater.php(180): Craft\MigrationsService->runToTop(Object(Craft\VzUrlPlugin))
#7 /home/vagrant/churchill/craft/app/services/UpdatesService.php(746): Craft\Updater->updateDatabase(Object(Craft\VzUrlPlugin))
#8 /home/vagrant/churchill/craft/app/controllers/UpdateController.php(405): Craft\UpdatesService->updateDatabase('vzurl')
#9 /home/vagrant/churchill/craft/app/framework/web/actions/CInlineAction.php(49): Craft\UpdateController->actionUpdateDatabase()
#10 /home/vagrant/churchill/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /home/vagrant/churchill/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /home/vagrant/churchill/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /home/vagrant/churchill/craft/app/framework/web/CWebApplication.php(282): CController->run('updateDatabase')
#14 /home/vagrant/churchill/craft/app/etc/web/WebApp.php(931): CWebApplication->runController('update/updateDa...')
#15 /home/vagrant/churchill/craft/app/etc/web/WebApp.php(262): Craft\WebApp->_processUpdateLogic()
#16 /home/vagrant/churchill/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#17 /home/vagrant/churchill/craft/app/index.php(62): CApplication->run()
#18 /home/vagrant/churchill/public/index.php(49): require_once('/home/vagrant/c...')
#19 {main}
in /home/vagrant/churchill/craft/app/etc/db/BaseMigration.php (55)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (149)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (91)
2017/02/16 21:28:28 [trace] [system.db.CDbTransaction] Rolling back transaction
in /home/vagrant/churchill/craft/app/etc/db/BaseMigration.php (59)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (149)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (91)
2017/02/16 21:28:28 [error] [application] Failed to apply migration: m170216_100000_vzurl_to_text_column (time: 0.002s)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (176)
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (91)
in /home/vagrant/churchill/craft/app/etc/updates/Updater.php (180)
2017/02/16 21:28:28 [error] [application] Migration failed for plugin VzUrl. All later VzUrl migrations are canceled.
in /home/vagrant/churchill/craft/app/services/MigrationsService.php (95)
in /home/vagrant/churchill/craft/app/etc/updates/Updater.php (180)
in /home/vagrant/churchill/craft/app/services/UpdatesService.php (746)
```

**Comment by elivz** [comment]
For the time being I just pushed a hot-fix that limits the migration to only individual URL fields, rather than sub-fields in Matrix, SuperTable, etc. It should update now for you. I'm undecided if I'll try to migrate all the possible nested field-types, since the logic would get very complex and I would need to track down all the 3rd-party plugins that might be creating their own content tables....

Of course, any new Matrix fields will use a TEXT column, without the character limit.

**Comment by bossanova808** [comment]
Just a note - same issue here, for presumably same reasons (extensive supertable & matrix use).  Basically just commenting to follow the thread ;)

**Comment by elivz** [comment]
@bossanova808 Are you using the current version from GitHub? That one *should* run, it just won't convert Matrix and Supertable cells to TEXT columns. If you are still getting an error with that version, I definitely want to know....

**Comment by bossanova808** [comment]
No - I rolled back to 1.0.3 for now as I had 7 other upgrades I didn't want to delay :)

All of these fields for me are in matrix or STs, so for now I just figured there's not much point to it for me...I'll pull master and get around to it later, but I wanted to follow along in case you release a fix for matrix/st - thanks!

**Comment by elivz** [comment]
Ah, gotcha. Yeah, I want to figure out a way to migrate those, it's just that Craft's database setup makes it very cumbersome. Each Matrix and SuperTable field creates its own table, which isn't connected via a shared value to the craft_fields table where I can see which cells are URL fields. So I'm probably going to have to do a bunch of extra processing in PHP, rather than a clean MySQL query.
